apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: failedbulkdemand
spec:
  schedule: "30 3 5 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: failedbulkdemand
            image: mgramseva/api-cronjob-image-4
            command: ["python3","cronJobAPIConfig.py"]
            args: ["fortnightevening"]  
            env:
              - name: JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
          restartPolicy: OnFailure            
